label story:
    # show sayori 1a at t11 zorder 1
    # s "Hey, I think I got the basics!"
    # show sayori at t21
    # s "Time to give up and \"play smash\""

    # play music t3
    # scene bg club_day
    # show monika 1a at t11
    # m "{b}Hi!{/b}"
    # m 1b "{i}What's up?{/i}"
    # m "I am-{nw}"
    # mc "Shush!"
    # m "{w=1}.{w=1}.{w=1}."
    # m "{w=1}.{w=1}.{w=1}.{nw}"
    # m "Oof!" (what_size=50, what_color="#32a852")

    # Every comment above is from tutorials, the code below is my attempt to convert the script.

    # Friday: The first part needs a lot of new assets, so many parts use wrong assets, FIX LATER
    $ mc_name = renpy.input("What is your name?")# Uncentered need to fix
    narrator "Friday"
    pause(2.0)
    scene bg corridor with dissolve_scene_full
    show yuri 1a at t21
    h "Hey buddy! Wake up!"
    narrator "I groan as I’m woken up from whatever wonderful dream I was having to somebody tapping me repeatedly on the shoulder. I look to my left to see a middle aged man hovering over me."
    h "Do you mind getting up for me pal? I’m trying to get to the bathroom and I don’t wanna climb over you."
    mc "Oh {w=1}…{w=1} uhhh sure."
    narrator "Just then, I hear a small ding as an announcement comes on the speaker."
    narrator "Attention everyone, this is your captain speaking. We will be making our descent shortly so, I’m going to need everyone to either return to or stay in your seats. Thank you and welcome to Sakura City!"
    narrator "I chuckle a little"
    mc "Sorry, guess not man."
    h "Damn."
    narrator "He sits down again looking defeated. I contemplate going back to sleep when the man opens the window next to his seat, blinding me with the bright light."
    narrator "I shrug it off and decide to take in the reality of my situation instead."
    mc "What the hell am I doing here?" (what_size = 10)
    narrator "I whisper this to myself but it appears the man next to me heard me speak."
    h "You talking to yourself buddy?"
    mc "I’m just trying to collect my thoughts."
    h "Long flight?"
    mc "More like a long week."
    h "I know how that feels. I think everybody’s had weeks like that."
    narrator "I nod. The conversation goes quiet for a while until the man speaks up again."
    h "So why are you traveling? Personally, I’ve come to see my family. I was supposed to be on a business trip but my daughter’s having some kinda crisis right now."
    h "Work is important but family comes first, you know?"
    mc "Yeah, I understand that. Family is important. Oh and I’m here for work actually."
    h "Work? Kid, you look way too young to have a job that requires you to travel."
    mc "Yeah, but this isn’t an ordinary job, and I’m not an ordinary worker."
    narrator "He raises his eyebrow curiously."
    h "Oh? What kind of job do you have?"
    mc "One that requires discretion."
    $ h_name = "Hayato"
    h "Hah! Now you’ve got me hooked. I like you kid. You seem like you’ve got a bright future ahead of you. Oh and my name’s Hayato by the way."
    mc "[mc_name]"
    narrator "We talk for a few more minutes before we finally land. I grab my two suitcases before quickly waving Hayato goodbye and exiting the plane. I get to street level and step outside to the pickup area."
    narrator "After a few mere seconds, a silver SUV pulls up in front of me. All the windows are tinted so that I can’t see inside. The window closest to me rolls down slightly and I hear a man's voice."
    r "You [mc_name]?"
    mc "Yup, and you are?"
    r "My name isn't something I give out so easily. Especially to a kid like you.  Get in"
    narrator "I put my bags in the trunk of the car and then attempt to open the passenger side door. It’s locked."
    r "The back."
    narrator "I open the back door and get in. There is a wall of tinted glass separating the back of the car from the front making me unable to see the driver. I close the door and the car starts to move."
    mc "Do you know where we’re going?"
    r "Yes."
    narrator "I figure that he isn’t in the mood for conversation so I wait patiently to arrive at my destination. Approximately forty minutes later, the car stops and the driver speaks up."
    scene bg house
    r "We’re here, get out."
    narrator "I exit the car and open the trunk. After taking my bags out and closing the trunk, the car immediately drives away."
    mc "What a prick."
    narrator "I look around and see that I’m in a residential neighborhood. Scanning the nearby houses for their addresses, I find the one I was supposed to go to."
    narrator "I take my bags and enter through the gate. I see a bald man with a black trench coat and sunglasses sitting on the steps next to the door. He has a black duffel bag and a brown suitcase which I recognize. It’s one of mine."
    mc "You don’t look suspicious at all!"
    narrator "The man chuckles for a little bit and then snaps right back to his serious demeanor."
    r "Here, I have your stuff."
    mc "Thanks, but how did you get that kinda tech here? I doubt it’s easy to transport without anyone noticing."
    r "Somethings in this world are better left unanswered. Ignorance is bliss after all. Let’s get inside."
    narrator "I walk to the door and set my two suitcases down next to it. I try the handle."
    mc "It’s locked."
    r "Here."
    narrator "The man reaches into his pocket and pulls out a set of keys, gently tossing them to me. However, before I unlock the door, I decide to inspect my lock. The lock looks weak and easy to pick."
    mc "This lock is terrible. Doubt it would stop anyone from breaking in."
    r "I doubt anyone is gonna try to break into your house."
    mc "You never know."
    narrator "I can replace the lock later but right now, I have more important things to do. I unlock the door and after grabbing my suitcases, head inside."
    narrator "The man still holding my third suitcase and the duffel bag follows me in. I place my suitcase in the living room and stretch. The man puts the third suitcase next to my other two."
    r "Did you get briefed on your mission?"
    mc "Only a couple hundred times."
    r "Well, you’ve got three weeks to complete it then."
    mc "Three weeks? I was told that I could take as much time as was necessary! You can’t just limit my time like that!"
    r "It was the boss, not me. He thinks that giving people too much time to accomplish something will only result in them slacking off. So, you’ve got three weeks. Problem?"
    narrator "I sigh in defeat."
    mc "Guess not. Whatever Hawk wants, Hawk shall receive. Alright, I’ve got planning to do so if you’re done, you can go now."
    r "I’m not done. There are a few other things I need to give you."
    narrator "He reaches into his jacket, pulling out a card and then handing it to me. On it, I see a username and password. He gives me another card also, this time a bank debit card."
    r "That’s the information for a bank account the boss is giving you. The money in that account is basically unlimited. However, you can ONLY use it for basic necessities and items for the mission."
    r "No personal luxuries! Your transactions will be monitored."
    mc "Fair enough."
    narrator "He then opens the duffel bag and reaches inside. He pulls out a phone, switchblade, and a gun. My eyes are locked on the gun. He places all three items on the nearby coffee table."
    mc "I do NOT need a gun. I’m not gonna hurt anybody. If all goes well, no one will even know I was there."
    r "And if things don’t go well, you’re going to need something that can get you out of a bad situation. Keep it and don’t be afraid to use it if needed."
    narrator "I pause, trying to figure out if I could even use a gun if I needed to. No, I can’t."
    mc "I’m not taking it."
    r "Yes you are. End of conversation."
    narrator "We both go quiet for a while. Then, he sighs and speaks up."
    r "Just take it. Keep it somewhere."
    mc "Fine! But I’m not using it!"
    r "Whatever."
    narrator "The man picks up the phone for me to see. It’s an old flip phone."
    r "You can use this to call the boss in case you need something extra to help you. Like extra resources or people. You’re also expected to call in to report on any progress you’ve made."
    r "The number is on the phone. Don’t make the boss wait. Understood?"
    narrator "I nod."
    r "Good. My number’s also on the phone but don’t call me. Chances are I won’t bother picking up. One more thing, your cover story."
    narrator "He reaches into the duffel bag again and pulls out ... a school uniform?"
    mc "What’s that for?"
    r "Like I said, you need a cover story in case anybody wonders why you’re here. There’s a local high school in the area so..."
    mc "HELL NO! You want me to complete this entire mission in three weeks while ALSO going to school? Why school anyway? Why not some other cover story? Perhaps something that provides me with more time to actually do my job!?"
    r "Look kid, you’re the perfect age to pose as a high school student and it’s the easiest and most reasonable thing we could come up with."
    r "Just go to school, come home and work on the mission. It’s a piece of cake! Plus, maybe you’ll make some new friends!"
    mc "Friends? Kids my age are annoying brats!"
    r "Yeah, I can tell."
    narrator "I sigh."
    mc "Ugh ... this job just keeps getting worse."
    r "Alright, I’ve done my part. I’ll let you get settled in."
    narrator "He leaves the uniform on the table and starts to walk back outside. I follow him to the door and lock it behind him."
    mc "Why did I sign up for this? Oh, right ... money. There’s still time left in the day. I should probably start unpacking."
    narrator "I unpack the two suitcases containing all my everyday items and decide to put the third one under my desk. It’s well into the evening and I think about what I should do next."
    narrator "All of a sudden, I hear someone burst into laughter from outside. I decide to take a peek and see two girls. One of them, clearly the source of that outburst, is bouncing around the other."
    narrator "She has coral pink hair with a red bow and bright blue eyes. The other girl who looks slightly concerned has brown hair tied into a ponytail with a white bow and beautiful green eyes."
    narrator "They’re both wearing uniforms similar to the one I got earlier so I’m assuming they’re students from the same highschool I’m supposed to be attending."
    narrator "I decided to crack open the window to better hear their conversation. After all, a little eavesdropping never hurt anybody."
    m "Sayori stop being so loud! People could be sleeping!"
    narrator "The other girl, apparently named Sayori, stops jumping and lowers her voice to a somewhat normal volume."
    s "Oh, I’m sorry Monika. I’m just super excited for the festival! Natsuki and Yuri are gonna love what we have planned. It’s gonna be so awesome!"
    $ m_name = "Monika"
    m "I know Sayori but you have to remember to be considerate of other people. I can’t blame you though. I’m also super excited for the festival."
    m "It’ll give people a chance to see what our club is really about! And then, we can all do something fun afterwards!"
    narrator "A festival? What are they talking about? Is there some kind of carnival in town? And what club are they in? My thoughts are cut short when they stop at one of the nearby houses."
    s "Welp, this is my place! Thanks again Monika! Club was extra special today! That story you picked out was amazing!"
    m "I’m just glad I could find something that both Natsuki and Yuri would read. There aren’t many stories that appeal to both of them."
    s "That’s what made today so fun! Everyone was participating in the conversation this time!"
    m "I just hope I can keep it up and find something else that interests everyone for next week."
    s "You can do it Monika! After all, you are the bestest president ever!"
    m "Thanks Sayori! It was fun talking to you! I should probably get going now though. See you later!"
    s "Bye Monika! Oh wait. Are you gonna get home alright? It’s kinda dark right now."
    m "Don’t worry, I’ll be fine! I promise!"
    s "Are you sure?"
    m "Yep! I’m perfectly capable of taking care of myself!"
    narrator "Monika gives Sayori a large, reassuring smile."
    s "Ok ... if you’re sure. Bye."
    m "See you later!"
    narrator "I shut my window. I don’t think that conversation was really worth eavesdropping on but, it doesn’t matter that much now. I need to focus. I don’t have much time to complete this mission. I need to create a plan."
    narrator "I grab a pencil and a piece of paper and decide to do some research. However, after opening my laptop, I see a bunch of news stories relating to events that occurred in this area, one in particular catching my eye."
    narrator "“LOCAL GANG FOUND BEATEN AND BRUISED IN WAREHOUSE AFTER DRUG DEAL” I click on it and decide to read through it."
    mc "How in the hell does an entire gang get beaten up like that? A rival gang maybe?"
    narrator "I stop. I’m distracting myself again. I need to focus! Time to get to work."
    narrator "Saturday"
    narrator "I wake up on my desk and open my eyes to the sunlight outside. I look at my phone. 7:32 A.M I stand up, yawn and stretch. After getting up, I realize that I’ve been drooling all over my plan. That’s fine."
    narrator "It’s not like it was a good plan anyway. I make my way to the bathroom and brush my teeth while trying to figure out what I’m going to do today. I get in the shower and turn it on."
    mc "Three weeks... Three weeks to complete the hardest mission of my life."
    narrator "My mind then starts to drift back to the article I read last night. How does an entire gang get beat up in their own warehouse? The thought of that scene sends a chill down my spine but I can’t let it get to me."
    mc "It doesn’t concern me. Three weeks and I’m outta here."
    narrator "I can’t let myself be distracted, I have a mission that I have to accomplish. I step out of the shower and hear my stomach grumble in despair."
    narrator "I didn’t eat dinner last night. I head downstairs and into the kitchen. I throw open the fridge door to take stock of what food I have."
    mc "Are you kidding me! They didn’t stock the fridge!?"
    narrator "I look into some of the cupboards in hope of finding something edible, but to no avail."
    mc "Looks like I’ll have to go and get some groceries. Ugh!"
    narrator "Groaning I grab the debit card, walk outside and start making my way toward the city. I’ll have to stumble upon a grocery store at some point."
    s "HEYYYYYYYY!"
    narrator "I jump in my skin as this scream pierces the air. I quickly turn around and see the same girl I saw last night, with the coral pink hair and sharp blue eyes."
    narrator "She sprints over to me in an overly energetic manner. As she gets closer, I can see that she has a muffin in her hand. She reaches me, out of breath."
    s "Hey, are you new to town? I haven’t seen you before!"
    mc "Um, who... uhh. Yeah I just moved in yesterday."
    narrator "Her enthusiastic demeanor concerns me. Who just runs up to random people in the streets?  That’s a quick way to be sold into the black market for sure."
    s "That’s great! I’m Sayori! It’s realllllllly nice to meet you!"
    mc "Nice to meet you too Sayori. My name’s [mc_name]."
    s "Are you headed into town by any chance? Do you need any help navigating?"
    narrator "At this point I am beyond the point of confusion, slowly treading into suspicion. Nobody is this friendly unless they want something. Or she could just be completely insane."
    mc "Thanks, but I’m going to have to decline. I was just headed to a grocery store to pick up some food. I had to skip dinner yesterday and breakfast today because I don’t have any food."
    narrator "Her eyes grow more sympathetic and she breaks off a piece of her muffin, holding it out to me. I hesitate for a moment before I graciously accept her gift."
    s "I hope you like blueberries!"
    narrator "I eat the small piece of blueberry muffin she handed me, savoring the sweet flavor. Sayori immediately gobbles up the rest of the muffin in a viscous fashion."
    narrator "Either she’s more hungry than I am or she really likes blueberry muffins."
    mc "Thank you for the muffin Sayori, but I should probably get going. I need to buy some groceries."
    narrator "I begin walking towards the city."
    s "Lemme guess, you have no clue where the local K-Mart is do you?"
    mc "What makes you think that?"
    s "You’re walking the wrong way. The city’s that way."
    narrator "She points down the street."
    s "C’mon, lemme show you where it is, you’ll get lost."
    narrator "I take out my phone and check the time. I guess it would be faster if I just allowed her to take me, faster than trying to find it by myself anyway."
    mc "Well I guess it would be a big help."
    narrator "Sayori’s face lights up in triumph."
    s "Let’s go!"
    narrator "She grabs hold of my wrist and begins rapidly pulling me towards the city. What in the world is wrong with this girl? She is actually kind of fast."
    narrator "Fortunately, my athletic skill allows me to keep up with her. We make our way through the city, ignoring the weird looks we get from the large crowds of people flooding the streets."
    narrator "Soon enough, we arrive at what looks like a grocery store. I shake my wrist free of Sayori’s grasp and turn to look at her. She looks exhausted and starts panting the moment we reach the front door, taking deep breaths in between words."
    s "We ... are ... here ... Let’s ... catch our breaths ... Phew ..."
    narrator "I contemplate going inside without her but I decide to be polite and wait for her to recover. About a minute later, she speaks up."
    s "Ok ... let’s go!"
    narrator "We enter and I grab one of the nearby grocery baskets. Sayori grabs one for herself as well. I guess she also has some shopping she needs to take care of."
    narrator "This shouldn’t take too long, I don’t need anything fancy, just the essentials. I head towards the fruit and vegetables section and begin picking out the best ones. I turn to see that Sayori isn’t near me."
    narrator "Where did she go? I shrug it off and continue with my shopping picking out everything I might need to stock my fridge."
    narrator "In addition to the fruits and veggies I already got, I gather bread, eggs, milk and cereal, different kinds of meats and even a bottle of soda to treat myself. Oh, and I can’t forget to buy some coffee."
    narrator "By the time I’m done, my basket is basically overflowing with food. I head to the checkout aisle and begin placing my food on the counter."
    narrator "As the grocery clerk swipes all my items, I turn to see Sayori happily trotting her way to me. I look over at the items in her basket and see nothing but snacks."
    narrator "Are you having a party or something?"
    s "Whaaa ... ?"
    narrator "She looks down at her basket."
    s "Oh, no. These are all for me!"
    narrator "This woman will have a heart attack by twenty-five. I decide not to comment on her dietary choices out of respect."
    s "Are you judging me?"
    mc "Well, if I’m being honest, chips, cookies and candy probably aren’t the healthiest foods you could eat."
    s "You make it sound like that’s all I’m getting."
    mc "Frozen pizzas aren’t much better for you either."
    s "But I like these foods!"
    mc "I’m not saying that you shouldn’t eat them, I’m just saying that you should probably have at least a few healthier items in your basket as well."
    s "Hehe ... you sound a lot like Monika."
    narrator "Monika is the girl she was with last night. Although, I should probably act like I don’t know who she’s talking about."
    mc "Who?"
    s "Monika! She’s my friend and also the president of my club for school. She always encourages me to eat healthier."
    mc "It sounds like she’s trying to look out for you."
    s "Yea, she’s super nice! And smart, and funny, and athletic, and a lot of other things."
    narrator "The clerk finishes swiping my items and I pay for them. I wait for the clerk to swipe Sayori’s items while we continue our talk."
    mc "It sounds like you look up to her."
    s "Yeah, she’s pretty amazing! Oh, and she always helps me with stupid stuff like homework and studying. Say, you’re about my age right? Are you gonna go to school at Cherry Blossom High?"
    mc "Yeah ... I guess I am."
    s "That’s soooo cool! Maybe we’ll be in the same class."
    mc "I certainly hope so!"
    narrator "I fake this enthusiasm. Personally, this girl seems like a headache and I’d prefer it if we never saw each other again. However, that situation seems unlikely due to the fact that we live right next to each other."
    narrator "The clerk finishes scanning Sayori’s items but as Sayori goes to pay, I notice a look of shock on her face."
    s "How is it that much!? Uhhhhh ..."
    narrator "Well, I guess she did help me to get to the store."
    mc "Hey so since you helped me here, I guess I’ll help you as thanks."
    s "Whaaaaaaa... "
    narrator "I give the clerk the organization's debit card and put all the snacks into a bag and hand it to her."
    s "THANK YOU!!!! You’re a lifesaver!"
    narrator "People near us jump and turn to look at her. I can’t believe how oblivious this girl is, almost like she's living in her own world."
    mc "Don’t worry about it. It’s not that big of a deal. Thank you again for your help, but I need to get going. I still have to cook."
    s "Well, thank you for the snacks and I guess we should start heading back."
    narrator "We start walking back home, and I notice that this bag is really quite heavy for her. She is struggling to keep up."
    mc "Let me hold that bag for you, looks like you’re struggling a little."
    s "Well, thank you."
    narrator "We walk in silence for a bit, it looks like Sayori is deep in thought about something. It was getting a little awkward so I struck up a conversation."
    mc "So how’s high school? Like is it a good high school, are the people nice and all?"
    s "You enrolled in a high school without knowing anything about it? Well, it's a good school. Your average high school I guess, nothing that special about it really."
    mc "Yeah, my moving here was a bit sudden, so I didn’t have time to do research."
    narrator "We eventually reached my house."
    mc "Alright this is my place. I guess I’ll see you around."
    s "Wait, gimme your number!"
    narrator "I look at her for a few seconds with a confused look on my face."
    s "What?!? You might need something else? How are you going to find your way around town, you might get lost or something."
    narrator "Resisting the urge to sock her, I force a smile."
    mc "You’re right, here."
    narrator "I hand her my phone and she puts in her number, tapping away at the screen."
    s "Here’s your phone. Wait! I have an idea!"
    narrator "Something tells me I’m not gonna like whatever crazy idea she’s come up with."
    s "What if I take you on a tour of the city tomorrow! That way I won’t have to worry about you getting lost. Oh, and we could also get to know each other better!"
    mc "I’ll pass."
    s "Whaaaaa ... ? But, it’ll be so much fun! We could go to the park, the arcade, and maybe even explore the city some more!"
    narrator "I attempt to think of some kind of excuse to get me out of this situation."
    mc "Sayori, you’ve already been a great help to me and I don’t want to take up any more of your precious time! You don’t have to worry about me at all."
    s "But I want to show you around! C’mon please! I promise you’ll have fun!"
    narrator "Wow. This girl is nothing if not persistent."
    mc "Sayori, no! I don’t want a tour!"
    narrator "I raise my voice slightly to get my point across. Although it looks like Sayori may have taken that a bit too personally."
    s "Oh ... ok. I’m sorry Player."
    narrator "Damn, I made her sad. I didn’t mean to hurt her feelings. Sure she’s kinda annoying but I don’t hate her or anything. Ugh, I’m gonna have to do this, aren’t I?"
    mc "Ok fine Sayori. I’ll let you take me on a tour."
    s "But ... you said ... "
    mc "Well, I changed my mind. A tour of the city would be lovely! Plus, the arcade sounds like a blast!"
    s "Are you sure?"
    mc "Absolutely!"
    narrator "Sayori’s smile returns and her eyes light up."
    s "Yay! It’s gonna be awesome! Get ready for the best day of your life."
    mc "I can’t wait!"
    s "Well, I should probably get going now. I’ll text you tomorrow!"
    mc "Alright, see you later."
    narrator "I hand her her bag and wave goodbye, watching her struggle with the bag home. I climb the steps to my house. I take a deep breath as I open the front door and get in."
    narrator "That was a lot more exhausting than I thought, socializing is wayyyy too hard, especially with someone like Sayori."
    mc "I guess I should put these groceries away."
    narrator "I put the groceries in the cupboards and the fridge. Now I won’t go hungry for a while and I can restock now that I know where the store is, unless the streets flood and I’m stuck here."
    narrator "That muffin wasn’t nearly enough to satiate me. I need a real breakfast."
    narrator "I grab four eggs from the fridge, bread, all the breakfast things you could think of to make a massive feast. I was starving, so you already know that I was looking forward to this meal."
    narrator "I made scrambled eggs, toast, tea, and bacon, piled it up on a plate and went to the dining table."
    mc "Thank god for food."
    narrator "I scarfed everything down at a pace considered hazardous, and before I knew it I was done. I let out a big sigh of satisfaction."
    narrator "Now that I’m on a full stomach, I can pick up where I left off on my research last night. Not that I made much progress."
    narrator "All I did was analyze some of the basic blueprints for the building that Hawk was able to provide me with. Looking at what he gave me only caused me to lose hope for this mission."
    narrator "The place is a fortress, one that not even I could break into undetected. I need to take a more creative approach to this mission. My usual tactics clearly aren’t going to cut it."
    narrator "I decide to research the building itself, Sanctuary, including its history, the different floors and its availability to the public."
    narrator "One of the most surprising facts to learn besides the fact that there are one hundred and two floors was that the fifty-second floor was actually open to the public, kinda."
    narrator "The floor serves as a fancy restaurant for the rich and elite. It’s called Crowned Courtesy. Not only are the prices well beyond what any normal person would consider reasonable, but the restaurant is invitation only."
    narrator "Thus, you can only get in if you have good connections or a high social status. The prices aren’t gonna be a problem for me but getting an invitation is gonna be damn near impossible."
    narrator "Maybe I could steal one? But I don’t know who’s on the guest list. While I’m trying to come up with a solid plan, I feel the organization’s flip phone start buzzing in my pocket."
    mc "Are they asking for a mission report already?"
    narrator "I hurriedly take out the phone and answer it."
    mc "Hello?"
    r "Hey kid, listen and save the questions for after I’m done."
    narrator "I recognize the voice. It’s the man who was at my house yesterday."
    mc "Why are you calling? I thought calls were for emergencies and reports only?"
    r "I said listen kid. Have you ever heard of a gang called the Red Roses?"
    mc "Can’t say that I have. Why?"
    r "Look, the gang got pummeled in one of their warehouses in the city recently."
    narrator "I shudder. I know exactly what gang he’s talking about now."
    mc "Yea I read an article on it actually. What about it?"
    r "Okay so basically everything that the gang had on them got confiscated, everything. I have connections in that gang, a cousin you could say."
    r "Now I for one don’t care all that much for this cousin, but he did have something valuable of mine."
    mc "Let me guess. And you want it back?"
    r "It’s a gold coin. It’s got a carving of a man on one side and a woman on the other. The police should have it in evidence lockup."
    r "I’d go and get it myself but, I’m no thief and I know you’re good at this kinda stuff. So whaddaya say kid? Help a brother out?"
    mc "What’s so special about this coin? If I’m going to risk jail time trying to get it, I wanna know what it’s worth."
    r "The man and woman on the coin, they’re my parents. This coin, it’s important to me. It’s all I’ve got left of em"
    mc "How did this cousin of yours even get a hold of your coin in the first place?"
    r "The bastard had something I needed, desperately. He knew how much that coin meant to me and he wanted to take it from me just for that."
    r "Kept the thing on him at all times so that he could rub it in my face whenever we had to talk. Honestly, I thought about beating him to a pulp and taking it a few times."
    mc "Why didn’t you?"
    r "He was part of a whole gang! I might’ve been furious, but I’m not stupid. To be honest, if you ask me, those guys got what was coming to them. I know it’s a lot to ask but, will you help me out kid?"
    mc "One more question. Does the organization know that you’re asking me about this?"
    r "No, this doesn’t involve them. They don’t need to know. Besides, you know Hawk. He’ll only complicate things."
    mc "Fine, I guess I could help you out."
    r "Thanks, I appreciate it."
    mc "No problem dude."
    r "Ren."
    mc "What?"
    $ r_name = "Ren"
    r "My name ... it’s Ren."
    mc "In that case, consider it done Ren."
    r "Alright, I’ll meet you at the station kid!"
    mc "Wait, what?"
    r "Relax, I’m not going to get in your way. I just want to be there."
    mc "Fine, see you there."
    narrator "I hang up. I guess the mission can wait. I should probably head to the station now. Wait, where is the station? I should’ve probably asked about that. I try calling Ren back. No answer."
    narrator "Damn. Well to find the coin I gotta find the station and I know someone who might know where it is. I pick up my phone and go to Sayori’s contact. I try to hit text but accidentally call her. Before I can hang up she answers the call."
    s "What, miss me already?"
    mc "Uhhh, hey... I wanted to ask you something real quick."
    narrator "I can’t believe she picked up in half a second, what, is she always on her phone?"
    s "Sure what's up?"
    mc "So hypothetically if I lose something I would want to go to the police station. Would you happen to know where it is?"
    s "You know that is really thoughtful of you."
    narrator "Sayori proceeds to tell me where the police station is. In Front of the laundromat and near the park, easy enough I guess."
    mc "Thanks Sayori, this is a big help."
    s "You can always count on your best friend."
    mc "Best friend? Sayori, we just met."
    s "Yeah, but we’re already so close!"
    narrator "This woman has a few screws loose."
    mc "Thanks again Sayori! Bye!"
    s "See you tomorrow player!"
    narrator "I hang up and contemplate the next part of my plan. Wait, I don't need a plan. I’ve done this hundreds of times, getting one small coin should be no trouble at all. I grab my sweater and head out."
    mc "Time to roll out."
    narrator "I walk to the police station using the address that Sayori gave me. I might have gotten lucky, she’s a useful tool to have around. As I get to the station, I see a familiar figure standing nearby. I catch his eye and beckon him over."
    r "Knew I could count on you kid."
    mc "Yeah, yeah, save the praise for later. Right now we have a job to accomplish."
    r "You’re the expert here, lead the way."
    mc "Simple, we go in there, take their keycard, get into the evidence room, get the coin, and we are out."
    r "Why do we need a keycard?"
    mc "Well the evidence room is going to have a keycard duh. Most of the police stations in Japan have installed keycard readers to further secure their evidence rooms after a bunch of evidence against a corrupt politician got destroyed a few years ago."
    r "Interesting. So I guess that's the plan, let's get this done."
    mc "We’re going to walk in there, but you do the talking. I don’t care how you do it, just stall for time."
    r "What’ll you be doing?"
    mc "Getting the keycard."
    narrator "Ren and I walk into the police station, with me being behind Ren’s big frame. I look around to see the station is mostly empty. There are a few cops in the hallway and a lady at the front desk."
    narrator "I notice a water fountain next to a filing cabinet near a few seats that I assume makes up the waiting area. Ren walks up to the desk."
    r "Hey uhh, I... I might have seen a robbery."
    
